spring:
  application:
    name: GFG Spring

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: S@r@th!2025
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update